library(shiny)
library(shinydashboard)
library(DT)

kickstarter <- read.csv(".\\data\\kickstarter_df2.csv")
kick_art <- read.csv(".\\data\\kickstarter_art.csv")
kick_comics <- read.csv(".\\data\\kickstarter_comics.csv")
kick_crafts <- read.csv(".\\data\\kickstarter_crafts.csv")
kick_dance <- read.csv(".\\data\\kickstarter_dance.csv")
kick_design <- read.csv(".\\data\\kickstarter_design.csv")
kick_fashion <- read.csv(".\\data\\kickstarter_fashion.csv")
kick_film <- read.csv(".\\data\\kickstarter_film.csv")
kick_food <- read.csv(".\\data\\kickstarter_food.csv")
kick_games <- read.csv(".\\data\\kickstarter_games.csv")
kick_journalism <- read.csv(".\\data\\kickstarter_journalism.csv")
kick_music <- read.csv(".\\data\\kickstarter_music.csv")
kick_photogaphy <- read.csv(".\\data\\kickstarter_photography.csv")
kick_publishing <- read.csv(".\\data\\kickstarter_publishing.csv")
kick_technology <- read.csv(".\\data\\kickstarter_technology.csv")
kick_theater <- read.csv(".\\data\\kickstarter_theater.csv")

dashboardPage(skin = "black",
  dashboardHeader(title = span(tagList(icon("kickstarter-k")))),
  dashboardSidebar(
    sidebarMenu(style = "position: fixed",
      menuItem("Home", tabName = "home", icon = icon("home")),
      menuItem("Categories", tabName = "cats", icon = icon("kickstarter-k"),
        menuSubItem("art", tabName = "art", icon = icon("palette")),
        menuSubItem("comics", tabName = "comics", icon = icon("comments")),
        menuSubItem("crafts", tabName = "crafts", icon = icon("pencil-ruler")),
        menuSubItem("dance", tabName = "dance", icon = icon("walking")),
        menuSubItem("design", tabName = "design", icon = icon("crop")),
        menuSubItem("fashion", tabName = "fashion", icon = icon("tshirt")),
        menuSubItem("film & video", tabName = "film", icon = icon("video")),
        menuSubItem("food", tabName = "food", icon = icon("utensils")),
        menuSubItem("games", tabName = "games", icon = icon("dice")),
        menuSubItem("journalism", tabName = "journalism", icon = icon("newspaper")),
        menuSubItem("music", tabName = "music", icon = icon("music")),
        menuSubItem("photography", tabName = "photography", icon = icon("camera")),
        menuSubItem("publishing", tabName = "publishing", icon = icon("book")),
        menuSubItem("technology", tabName = "technology", icon = icon("laptop")),
        menuSubItem("theater", tabName = "theater", icon = icon("theater-masks"))),
      menuItem("Campaign Length", tabName = "campaign", icon = icon("calendar-alt")),
      menuItem("Analysis", tabName = "analysis", icon =icon("chart-bar")),
      menuItem("Project Evaluator", tabName="project", icon = icon("money-bill-alt"))
    )
  ),
   dashboardBody(
      tabItems(
        tabItem(tabName = "home",
          img(src="title.png", alt = "title", height = 100)
        ),
        
        tabItem(tabName = "art",
          img(src="art.png", alt = "art", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("art"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("art_camp"),
          br(),
          sliderInput("art_lim", label="pledge range", min=0, max= 2000000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("art_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("art_stat")
        ),
        
        tabItem(tabName = "comics",
          img(src="comics.png", alt = "comics", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("comics"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("comics_camp"),
          br(),
          sliderInput("comics_lim", label="pledge range", min=0, max= 1300000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("comics_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("comics_stat")

        ),
        
        tabItem(tabName = "crafts",
          img(src="crafts.png", alt = "crafts", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("crafts"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("crafts_camp"),
          br(),
          sliderInput("crafts_lim", label="pledge range", min=0, max= 460000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          br(),
          selectizeInput("crafts_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          plotOutput("crafts_stat")

        ),
        
        tabItem(tabName = "dance",
          img(src="dance.png", alt = "dance", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("dance"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("dance_camp"),
          br(),
          sliderInput("dance_lim", label="pledge range", min=0, max= 150000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("dance_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("dance_stat")

        ),
        
        tabItem(tabName = "design",
          img(src="design.png", alt = "design", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("design"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("design_camp"),
          br(),
          sliderInput("design_lim", label="pledge range", min=0, max= 2050000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("design_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("design_stat")

        ),
        
        tabItem(tabName = "fashion",
          img(src="fashion.png", alt = "fashion", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("fashion"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("fashion_camp"),
          br(),
          sliderInput("fashion_lim", label="pledge range", min=0, max= 4000000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("fashion_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("fashion_stat")

        ),
        
        tabItem(tabName = "film",
          img(src="film.png", alt = "film", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("film"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("film_camp"),
          br(),
          sliderInput("film_lim", label="pledge range", min=0, max= 6000000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("film_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("film_stat")

        ),
        
        tabItem(tabName = "food",
          img(src="food.png", alt = "food", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("food"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("food_camp"),
          br(),
          sliderInput("food_lim", label="pledge range", min=0, max= 2000000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("food_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("food_stat")

        ),
        
        tabItem(tabName = "games",
          img(src="games.png", alt = "games", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("games"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("games_camp"),
          br(),
          sliderInput("games_lim", label="pledge range", min=0, max= 12500000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("games_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("games_stat")

        ),
        
        tabItem(tabName = "journalism",
          img(src="journalism.png", alt = "journalism", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("journalism"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("journalism_camp"),
          br(),
          sliderInput("journalism_lim", label="pledge range", min=0, max= 750000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("journalism_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("journalism_stat")
        ),
        
        tabItem(tabName = "music",
          img(src="music.png", alt = "music", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("music"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("music_camp"),
          br(),
          sliderInput("music_lim", label="pledge range", min=0, max= 1400000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("music_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("music_stat")

        ),
        
        tabItem(tabName = "photography",
          img(src="photography.png", alt = "photography", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("photography"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("photography_camp"),
          br(),
          sliderInput("photography_lim", label="pledge range", min=0, max= 800000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round = 10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("photography_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("photography_stat")

        ),
        
        tabItem(tabName = "publishing",
          img(src="publishing.png", alt = "publishing", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("publishing"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("publishing_camp"),
          br(),
          sliderInput("publishing_lim", label="pledge range", min=0, max= 900000, width = "100%", 
                      sep =",", value =c(0,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("publishing_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("publishing_stat")

        ),
        
        tabItem(tabName = "technology",
          img(src="technology.png", alt = "technology", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("technology"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("technology_camp"),
          br(),
          sliderInput("technology_lim", label="pledge range", min=0, max= 6300000, width = "100%", 
                      sep =",", value = c(min,max), step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("technology_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("technology_stat")

        ),
        
        tabItem(tabName = "theater",
          img(src="theater.png", alt = "theater", height = 100),
          br(),
          br(),
          img(src="tppy.png", alt = "total pledge", height = 60),
          br(),
          plotOutput("theater"),
          br(),
          br(),
          img(src="camp_len.png", alt = "campaign length", height = 60),
          br(),
          plotOutput("theater_camp"),
          br(),
          sliderInput("theater_lim", label="pledge range", min=0, max= 400000, width = "100%", 
                      sep =",", value =c(0,max),step=10000, round =10000, ticks=TRUE, 
                      dragRange=TRUE),
          br(),
          br(),
          img(src="sub_cats.png", alt = "sub categories", height = 60),
          selectizeInput("theater_stat_1", "Sort by:", choices= c("successful","failed","canceled"),selected="successful"),
          br(),
          plotOutput("theater_stat")

        ),
        
        tabItem(tabName = "campaign",
          img(src = "camp_len.png", alt= "campaign_length", height = 100),
          plotOutput("len_camp")
          
        ),
        
        tabItem(tabName = "analysis",
          img(src = "analysis.png", alt= "analysis", height = 100)
                
        ),
        
        tabItem(tabName = "project",
          img(src = "construction.png", align = "center")
        )
      )
  )
)